### ISSUE TITLE
Have you successfully written the firmware?

### ISSUE THREAD

**Issue by TL730** [RomanButsiy/RFDLoader#1]
I tried to build my own cyton board, but the firmware could not be written to the board and dongle. I once suspected that the purchased Bluetooth module rfd22301 was fake.

I saw your message in the Forum on the openbci official website. You gave a solution that the Bluetooth module cannot write firmware. Have you successfully written the firmware?

**Comment by RomanButsiy** [comment]
I guess my Bluetooth module rfd22301 was probably a fake too. Yes, I successfully written the firmware.

To test, I wrote `RadioDevice32bit` firmware to the second module and connected it via USB-UART to another PC. I was able to transmit messages at a distance of up to two meters

**Comment by TL730** [comment]
your rfd22301 module can work normally after it is successfully written to the firmware! Cyton and dongle can transmit data - only at a distance of up to 2 meters - that mean it's fake. So, is the display normal on the openbci GUI?

**Comment by TL730** [comment]
The distance of 2 meters is a little too close.

**Comment by TL730** [comment]
Rfd22301 has been discontinued and is becoming more and more difficult to buy. The best way is to consider replacing it with other mainstream Bluetooth modules.

Rfd22301 itself is relatively expensive. I don't know why I chose it at that time. What are its advantages?

**Comment by RomanButsiy** [comment]
I can't say anything about its advantages, the usual Bluetooth module

**Comment by TL730** [comment]
I think the CC series of Texas Instruments should also be OK

**Comment by TL730** [comment]
I replaced the files in C: \ program files (x86) \ Arduino \ hardware \ Arduino \ rfdino with your rfdloader.exe, and then uploaded:
Timeout reading from uart.

fail.......fail.......fail.......

**Comment by RomanButsiy** [comment]
Most likely there is no connection with Rfd22301. Check the pins RX, TX, RST, 3.3V. 
RX to TX, TX to RX, DTR through a capacitor to RST

**Comment by TL730** [comment]
I just plug dongle into my windows 10 computer and upload the radio firmware to the dongle host.

**Comment by TL730** [comment]
I built the dongle myself according to the official website. I wonder if the rfd22301 I bought is fake?

**Comment by TL730** [comment]
![无标题](https://user-images.githubusercontent.com/45458131/129713354-c9f877e6-1671-41d7-8cb7-56c54b324f6c.png)

**Comment by TL730** [comment]
The above figure shows the results obtained without replacing rfdloader.exe.

**Comment by RomanButsiy** [comment]
Check that the switch is in position RST. What is the capacitance of capacitor C5. On a forum wrote that at people the capacitor with a capacity of 0.01 uF did not work. I tried capacitors with a capacity of (0.01, 0.1, 0.2) uF, and with each of them I was able to upload firmware. Now it's hard for me to say what's wrong, but I think the problem is hardware

**Comment by TL730** [comment]
According to the official website tutorial, the switch is in RST position. Capacitor C5 is 0.01uF in the BOM provided on the official website. Why can you upload firmware?

**Comment by TL730** [comment]
![8dbdc9d2727b50eaaf4ff8f78f447a3](https://user-images.githubusercontent.com/45458131/129844095-9dfdce8f-673f-4e72-9dbd-60b9821b7e6c.jpg)

**Comment by RomanButsiy** [comment]
I used the scheme from the official website to create [my own pcb](https://easyeda.com/Targaryen/OpenBCI-dongle). It was due to the fact that I could not find the FT231 in the right case and some other parts in the shops of my city. I would recommend checking that all the required signals reach the RFD22301. Check the values of resistors, capacitors. I once had a case where a new smd resistor just came out of the package, found faulty. I then for a few days could not understand why the circuit works incorrectly. I hope you can find out the reason

![photo_2021-08-18_10-12-14](https://user-images.githubusercontent.com/38099410/129858482-c113f1b0-03a9-4ca2-9711-19be7b61d2e7.jpg)

**Comment by TL730** [comment]
Did you successfully upload the firmware? Data flow within 2 meters? Can you connect to the GUI?

**Comment by TL730** [comment]
您真是厉害的高手！我是个初级选手。
您建议建议检查所有要求的信号是否到达RFD22301。检查电阻器、电容器的值。所有要求的信号是哪些？具体如何检查电阻器、电容器的值？

**Comment by TL730** [comment]
You are a great master! I'm a beginner.

You are advised to check whether all required signals reach rfd22301. Check the value of resistor and capacitor. What are all the required signals? How to check the values of resistors and capacitors?

**Comment by TL730** [comment]
Rfduino electronic prototype platform is developed by an electronic store called open source RF. According to the development store, rfduino is only the size of fingertip, equipped with Nordic 32-bit arm Cortex-M0 processor, 7 bus extenders (Digital IO, analog ADC, SPI, I2C, UART and PWM), with Arduino controller function, built-in Bluetooth 4.0, a USB interface and a hard coin sized battery.

**Comment by TL730** [comment]
I bought the dongle board on the official website and made it myself.

The rfd22301 module on the dongle board I purchased on the official website is welded to the dongle board I made, and the firmware can be uploaded. The rfd22301 module purchased by yourself is welded on the board purchased on the official website, and the firmware cannot be uploaded.

So I suspect it's the Bluetooth module I bought. The batch numbers I purchased are 1533, 1545 and 1611.

**Comment by TL730** [comment]
I bought the dongle board on the official website.

At the same time, I also made a dongle board myself.

The rfd22301 module on the dongle board I purchased on the official website is welded to the dongle board I made, and the firmware can be uploaded. The rfd22301 module purchased by yourself is welded on the board purchased on the official website, and the firmware cannot be uploaded.

So I suspect it's the Bluetooth module I bought. The batch numbers I purchased are 1533, 1545 and 1611.

**Comment by RomanButsiy** [comment]
> You are advised to check whether all required signals reach rfd22301. Check the value of resistor and capacitor. What are all the required signals? How to check the values of resistors and capacitors?

Check if rfd22301 is receiving power. I use such a multimeter. Bought it about 12 years ago. It was the only one sold in a radio shop at the time
![photo_2021-09-05_13-57-18](https://user-images.githubusercontent.com/38099410/132124311-c87072a9-1474-48bd-97e3-6d090c91a9b8.jpg)

> Did you successfully upload the firmware? Data flow within 2 meters? Can you connect to the GUI?

Data transmission works at a distance of a meter. At a greater distance, the speed decreases. 😕
![Знімок екрану з 2021-09-01 11-43-53](https://user-images.githubusercontent.com/38099410/132125157-38a98a49-251e-4e92-9fac-f6899b6bbd8b.png)

**Comment by TL730** [comment]
> > 建议您检查是否所有需要的信号都到达rfd22301。检查电阻和电容的值。所有需要的信号是什么？如何检查电阻和电容的值？
> 
> 检查 rfd22301 是否通电。我使用这样的万用表。大约12年前买的。这是当时唯一在收音机商店出售的
> ![照片_2021-09-05_13-57-18](https://user-images.githubusercontent.com/38099410/132124311-c87072a9-1474-48bd-97e3-6d090c91a9b8.jpg)
> 
> > 固件上传成功了吗？2米以内的数据流？你能连接到GUI吗？
> 
> 数据传输在一米的距离内工作。距离越远，速度越慢。😕
> ![Знімок екрануз 2021-09-01 11-43-53](https://user-images.githubusercontent.com/38099410/132125157-38a98a49-251e-4e92-9fac-f6899b6bbd8b.png)

**Comment by TL730** [comment]
Check whether rfd22301 is powered on——That's a good idea. I'm going to try.
Data transmission works within a distance of one meter. The farther the distance, the slower the speed——It seems that your rfd22301 is not very easy to use
